[package]
name = "fuzzer"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chewing = { version = "0.9.1", path = ".." }
chewing_capi = { version = "0.9.1", path = "../capi" }
log = "0.4.21"
env_logger = { version = ">= 0.10.2", default-features = false }
